/*
 * Copyright (C) 2026 European Union
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence"); You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an
 * "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the Licence for
 * the specific language governing permissions and limitations under the Licence.
 */

package eu.europa.ec.itb.validation.commons.jar;

import java.io.File;

/**
 * Captures the provided input and the input file name. The file name may be one
 * generated by the validator in case the input is not provided from the file system.
 */
public class ValidationInput {

    private final File inputFile;
    private final String fileName;

    /**
     * Constructor.
     *
     * @param inputFile The input file.
     * @param fileName The file name.
     */
    public ValidationInput(File inputFile, String fileName) {
        this.inputFile = inputFile;
        this.fileName = fileName;
    }

    /**
     * @return The input file.
     */
    public File getInputFile() {
        return inputFile;
    }

    /**
     * @return The file name.
     */
    public String getFileName() {
        return fileName;
    }
}
